### ISSUE TITLE
Reading Binance API [Project Item]

### ISSUE THREAD

**Issue by sandy1618** [ping-trade-io/DataStore-Query#5]
### Description : 
The focus will be getiing familiar with binance api and getting very specific data 

### What is to be done ?
Getting Data of the Volume , the order information per 1m , 5m , 15m, 30m and 4 hrs.

### What does it affect ? 

It effects the main pinging algorithm

### Please assign task and mention project name as Site-Backend Framework Project. See the right side bar.

**Comment by TohokuBlockchainGroup** [comment]
Good @sandy1618, Please post your queries below or in [Team-Discuss](https://github.com/orgs/ping-trade-io/teams/ping-trade-io-devs)

**Comment by TohokuBlockchainGroup** [comment]
@sandy1618, As discussed, we will need candlestick data from binance as of now. Thanks for informing me.

**Comment by sandy1618** [comment]
One Specific Volume indicator issues solved.

**Comment by TohokuBlockchainGroup** [comment]
Okay.
